FROM pytorch/pytorch:2.1.0-cuda12.1-cudnn8-runtime
RUN apt-get update && apt-get install -y poppler-utils libgl1 libglib2.0-0 && rm -rf /var/lib/apt/lists/*
RUN pip install ultralytics pdf2image pillow requests sqlite-utils patool
WORKDIR /app
